**01. 데이터 로딩**

In [1]:
# 라이브러리
import numpy as np
import pandas as pd

# 데이터 로딩
dataset = pd.read_csv('./data/final_dataset.csv')

# 불필요한 열 제거
del dataset['Unnamed: 0']

# 데이터 보기
dataset

open  high   low  close  trading_volume  score  index  probability  \
0        -4.33 -2.76 -2.76  -1.02           12.59   1.33   0.89        47.11   
1         1.34  0.41 -8.52  -6.68           13.34   1.64   0.67        27.96   
2       -11.08 -4.34  0.57   3.52           12.72   1.60   0.63        23.64   
3         5.26  3.06  5.26   3.83           12.55   1.60   0.63        23.64   
4         6.95  3.38  5.32  -0.10           12.77   1.60   0.63        23.64   
...        ...   ...   ...    ...             ...    ...    ...          ...   
1901794  -0.37 -0.47 -0.17   0.34            6.99   7.96   2.40        79.01   
1901795   0.68  0.84  0.27   0.00            8.27   7.91   3.04        79.75   
1901796  -1.04 -1.07 -0.64  -0.03            7.44   7.91   3.04        79.75   
1901797  -0.31 -1.11 -0.92  -1.48            6.19   7.90   1.95        77.30   
1901798  -0.17  4.53 -1.03   4.92            9.11   7.90   3.04        79.75   

           l1    l2    l3     l4  lgap  lrate    zone  
0       -1.92 -1.90 -1.89  -1.87  6.29    6.0  Danger  
1        1.20 -3.11 -7.59 -12.24  7.50   20.0  Danger  
2       -2.92 -0.58  2.08   5.13  7.00   12.0  Danger  
3        2.45  3.44  4.52   5.68  6.73    9.0  Danger  
4        0.80  1.64  2.53   3.48  6.40    6.0  Danger  
...       ...   ...   ...    ...   ...    ...     ...  
1901794 -0.22 -0.07  0.08   0.24  5.28    1.0    Good  
1901795  0.70  0.42  0.14  -0.15  5.78    2.0  Danger  
1901796 -0.76 -0.55 -0.34  -0.12  5.42    2.0  Danger  
1901797 -1.39 -1.30 -1.20  -1.11  5.20    1.0  Danger  
1901798  7.48  4.73  1.95  -0.84  7.25    9.0    Good  

[1901799 rows x 15 columns]

**02. 데이터 분리**

In [2]:
# Input Target 분리
X = dataset[dataset.columns[:-1]]
Y = dataset[dataset.columns[-1:]]

# Train, Valid, Test 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10, random_state=1234)
X_train, X_valid, Y_train, Y_valid = train_test_split(X_train, Y_train, test_size=0.10, random_state=1234)

# 각 데이터셋별 관측치 수
print('Train = {:,} obs \t Valid = {:,} obs \t Test = {:,} obs'\
                               .format(X_train.shape[0],X_valid.shape[0],X_test.shape[0]))

# 각 데이터셋별 관측치 수 (비율)
total_len = len(dataset)
train_len = len(X_train)
valid_len = len(X_valid)
test_len = len(X_test)
print('Train = {:.2f} % \t Valid = {:.2f} % \t Test = {:.2f} %'
             .format(100*train_len/total_len, 100*valid_len/total_len, 100*test_len/total_len))

Train = 1,540,457 obs 	 Valid = 171,162 obs 	 Test = 190,180 obs
Train = 81.00 % 	 Valid = 9.00 % 	 Test = 10.00 %


**03. Random Forest**

In [5]:
# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
randomforest = RandomForestClassifier(max_depth=10, random_state=1234)
randomforest.fit(X_train, Y_train)

/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1234,
                       verbose=0, warm_start=False)

In [6]:
# Train Confusion Matrix
Y_pred = randomforest.predict(X_train)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_train, Y_pred), end='\n\n')

# Valid Confusion Matrix
Y_pred = randomforest.predict(X_valid)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_valid, Y_pred), end='\n\n')

# Test Confusion Matrix
Y_pred = randomforest.predict(X_test)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred), end='\n\n')

[[1129877    1866     111]
 [ 358929   25444     244]
 [  23194     315     477]]

[[125398    239     14]
 [ 40021   2806     30]
 [  2554     38     62]]

[[139281    236     14]
 [ 44579   3042     47]
 [  2882     41     58]]

