### 텐서플로우 2.0

In [0]:
# Tensorflow 버전 변경
try : 
  %tensorflow_version 2.x
except Exception : 
  pass

import tensorflow as tf

In [46]:
# 버전 확인
import tensorflow as tf
print(tf.__version__)

2.1.0


### 난수생성


In [47]:
# 균등분포 난수 생성
rand = tf.random.uniform([1], 0, 1)
print(rand)

tf.Tensor([0.7289027], shape=(1,), dtype=float32)


In [48]:
# 균등분포 난수 생성
rand = tf.random.uniform([4], 0, 1)
print(rand)

tf.Tensor([0.02099311 0.12969947 0.8165736  0.36137152], shape=(4,), dtype=float32)


In [49]:
# 정규분포 난수 생성
rand = tf.random.normal([4], 0, 1)
print(rand)

tf.Tensor([ 0.06472187  0.3899432  -1.1655881  -1.7830234 ], shape=(4,), dtype=float32)


### 시그모이드 

In [0]:
# 시그모이드 함수를 정의
import math
def sigmoid(x) : 
  return 1 / (1 + math.exp(-x))

In [51]:
# x=1과 랜덤으로 생성한 값인 w를 곱한 값을 시그모이드 함수에 집어 넣어 y=0과 에러를 비교
x = 1
y = 0
w = tf.random.normal([1], 0, 1)
output = sigmoid(x * w)
print(output)

0.27648022707770203


### 뉴런의 구조

In [52]:
# 입력이 1, 출력이 0이되는 뉴런

for i in range(1000) : 

  # 시그모이드를 이용하여 값 계산 
  output = sigmoid(x * w)
  # 실제값과의 오차 계산
  error = y - output
  # 실제값의 차이를 줄이는 방향으로 가중치(w) 조정
  w = w + x * 0.1 * error
  # 100번째마다 실행 결과 출력
  if i % 100 == 99 : 
    print(i, error, output)

99 -0.08244032391155014 0.08244032391155014
199 -0.046412888979094125 0.046412888979094125
299 -0.03207213260854848 0.03207213260854848
399 -0.024441650108094976 0.024441650108094976
499 -0.019721875079338664 0.019721875079338664
599 -0.016519769108710326 0.016519769108710326
699 -0.014206970921128253 0.014206970921128253
799 -0.012459283590211825 0.012459283590211825
899 -0.01109265631030566 0.01109265631030566
999 -0.00999503403744611 0.00999503403744611


In [53]:
# 입력이 0, 출력이 1 이되는 뉴런
x = 0
y = 1
w = tf.random.normal([1], 0, 1)

for i in range(1000) : 

  # 시그모이드를 이용하여 값 계산 
  output = sigmoid(x * w)
  # 실제값과의 오차 계산
  error = y - output
  # 실제값의 차이를 줄이는 방향으로 가중치(w) 조정
  w = w + x * 0.1 * error
  # 100번째마다 실행 결과 출력
  if i % 100 == 99 : 
    print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [0]:
# x=0일 때  y=1을 얻는 뉴런의 학습에 편향을 더함
x = 0
y = 1
w = tf.random.normal([1], 0, 1)
b = tf.random.normal([1], 0, 1)

for i in range(1000) : 
  output = sigmoid(x * w + 1 + b)
  error = y - output
  w = w + x  *